{
 "title": "IPFS Realtime Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Intro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# IPFS Monitoring Metrics\n\nVarious metrics extracted from IPFS nodes with unlimited connection capacity and the messages they receive.\n\n### Research Work\n\nAs a complement to this interactive dashboard, please have a look at our paper titled [Monitoring Data Requests in Decentralized Data Storage Systems: A Case Study of IPFS](https://arxiv.org/abs/2104.09202), which will be publish at this year's [ICDCS](https://icdcs2022.icdcs.org/) conference.\nFeel free to contact me (see below) with any questions or comments!\n\n### Metrics\n\nWe use and display:\n- Metrics built into IPFS\n- Real-time analyses of incoming Bitswap traffic, performed by our [real-time analysis client](https://github.com/trudi-group/ipfs-tools/tree/master/bitswap-monitoring-client)\n- Metrics about/extracted from the IPFS node added by our [plugin](https://github.com/trudi-group/ipfs-metric-exporter), and about the plugin state itself\n\n**Most visualizations have a description.**\nYou can view that with the tiny `i` in the top-left corner of the visualization.\n\n#### Visualization Options\n\nYou can find a selector for the **visualized time range for all visualizations** in the top right-hand corner of the page.\nNext to that you can switch to **kiosk mode** to remove some more visual clutter, but this is of course optional.\nIn addition to that, each plot can be\n- viewed in full-screen mode by pressing `V` on its title-bar (or selecting \"View\" from its menu)\n- selected to show only specific time-series by clicking them in the legend. Multiple series can be selected by holding `Shift` while clicking\n- used to select a time range to display by selecting it with the mouse in the visualization\n\n#### Sections\n\nThis dashboard consists of multiple collapsible sections.\nEach section usually has some information about the data displayed and methodology used to obtain it.\nYou can also collapse this message using the \"Intro\" section above it.\nCollapsing sections helps performance, both on your and our end.\n\n### Setup\n\nWe're using [this docker compose](https://github.com/trudi-group/ipfs-metric-exporter/tree/master/docker-compose) setup.\nWe are continuously updating our infrastructure to keep up-to-date with latest releases of kubo and new features.\n\n#### Datasets\n\nThe data visualized here is produced and consumed in real-time, and stored in prometheus.\nWe also have large traces of Bitswap traffic.\nIf you're interested in any of the data, or have questions about it, please don't hesitate to contact me (see below).\nSee also our [privacy policy](https://monitoring.ipfs.trudi.group/privacy_policy.html) about data retention and usage policies.\n\n### Contact/See also\n\nBy Leo @ [Team TruDi](https://trudi.group), Berlin/Darmstadt.\nContact me via [email](mailto:leonhard.balduf@tu-darmstadt.de).\nSee also:\n- The [plugin](https://github.com/trudi-group/ipfs-metric-exporter) we develop to do this\n- The [analysis client](https://github.com/trudi-group/ipfs-tools/tree/master/bitswap-monitoring-client) used to ingest Bitswap traffic\n- The [size estimator](https://github.com/trudi-group/ipfs-tools/tree/master/monitoring-size-estimator) we use to estimate network size"
   }
  },
  { "title": "Size Estimates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "### Network Size Estimates\n\nEstimates of the total network size and the size of peer populations supporting given protocols.\nThis is calculated using the [monitoring size estimator](https://github.com/trudi-group/ipfs-tools/tree/master/monitoring-size-estimator) tool.\n\n#### Estimated Sizes\n\nThis estimates the size of the entire IPFS network, including DHT servers and clients.\n\nFor specific protocols, the two samples obtained by the monitor are filtered for peers indicating support for the given protocol.\nThese filtered samples are then used to estimate the total size of the subset of peers of the IPFS network supporting the given protocol.\n\nFurthermore, we estimate the size of the network populace running a given agent version using the same approach.\nThis should, in theory, categorize the network into disjoint sets, which in sum should add up to the entire network size.\nAs can be seen, this does not hold.\nWe suspect that these samples are not uniform for every agent version, i.e., some agents have a bias in their connection preference.\n\n#### Estimators\n\nWe implement two estimators:\n- A hypergeometric estimator which is fast and simple, but only works for pairs of monitors.\n  For this estimator, we evaluate all pairs of monitors.\n- An estimator based on the coupon collector's problem.\n  This needs to be solved numerically and is somewhat slow, doesn't always return a result, but can operate on arbitrarily large sets of monitors.\n  As a simplification, we use the average number of peers over all monitors as the number of connections per monitor.\n\nFor details, please read our [paper](https://arxiv.org/abs/2104.09202).\n\n#### Caveats\n\nBoth estimators assume uniform sampling.\nWe have confirmed that this holds for large monitoring nodes, which makes estimates of the total network size probably somewhat accurate.\nThis also means that for protocols without special peer selection, accurate estimates are possible.\n\nHowever, this **does not work for subsets of peers with non-uniform connectivity**.\nIn particular, this **does not work for DHT size estimations**, because Kademlia connection are not a uniform sample of the total peer population.\n\nIt also looks like it **does not work for all agent versions**."
   }
  },
  {
   "title": "Average Network Size Estimate",
   "type": "stat",
   "description": "Averages over all monitor pairs of the hypergeometric estimator and the coupon collector estimator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg((monitoring_size_estimator_hypergeom_size_estimate{protocol=\"\", agent_version=\"\"} > 1)) by (instance, job) +  (monitoring_size_estimator_coupon_size_estimate{protocol=\"\",agent_version=\"\"}>1))/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Peer Population Estimates by Agent Version, Top 10, Average over Estimators",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,(avg(monitoring_size_estimator_hypergeom_size_estimate{protocol=\"\", agent_version!=\"\"}) by (instance, job,agent_version) +  monitoring_size_estimator_coupon_size_estimate{protocol=\"\",agent_version!=\"\"})/2)",
     "legendFormat": "{{agent_version}}"
    }
   ]
  },
  {
   "title": "Size Estimates for Agent Versions, Hypergeometric Estimator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "monitoring_size_estimator_hypergeom_size_estimate{protocol=\"\",agent_version!=\"\"}",
     "legendFormat": "{{agent_version}}, {{monitor_pair}}"
    }
   ]
  },
  {
   "title": "Size Estimates for Agent Versions, Coupon Collector Estimator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "monitoring_size_estimator_coupon_size_estimate{protocol=\"\",agent_version!=\"\"}",
     "legendFormat": "{{agent_version}}"
    }
   ]
  },
  {
   "title": "Size Estimates per Protocol, Hypergeometric Estimator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(monitoring_size_estimator_hypergeom_size_estimate{protocol!=\"\",protocol!~\".*kad.*\",agent_version=\"\"}) by (protocol,monitor_pair)",
     "legendFormat": "{{protocol}}, {{monitor_pair}}"
    }
   ]
  },
  {
   "title": "Size Estimates per Protocol, Coupon Collector Estimator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(monitoring_size_estimator_coupon_size_estimate{protocol!=\"\",protocol!~\".*kad.*\",agent_version=\"\"}) by (protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Agent Version Population Sizes, Average over Estimators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "(avg(monitoring_size_estimator_hypergeom_size_estimate{protocol=\"\", agent_version!=\"\"}) by (instance, job,agent_version) +  monitoring_size_estimator_coupon_size_estimate{protocol=\"\",agent_version!=\"\"})/2",
     "legendFormat": "{{agent_version}}"
    }
   ]
  },
  {
   "title": "Size Estimates for the Entire Network by Estimator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "monitoring_size_estimator_hypergeom_size_estimate{protocol=\"\",agent_version=\"\"} > 1",
     "legendFormat": "Hypergeometric Estimator, {{monitor_pair}}"
    },
    {
     "expr": "monitoring_size_estimator_coupon_size_estimate{protocol=\"\",agent_version=\"\"} > 1",
     "legendFormat": "Coupon Collector Estimator"
    },
    {
     "expr": "sum(monitoring_size_estimator_coupon_size_estimate{protocol=\"\",agent_version!=\"\"})",
     "legendFormat": "Coupon Collector Estimator, Sum over all Agent Versions"
    },
    {
     "expr": "sum(avg(monitoring_size_estimator_hypergeom_size_estimate{protocol=\"\",agent_version!=\"\"}) by (agent_version,monitor_pair)) by (monitor_pair)",
     "legendFormat": "Hypergeometric Estimator, Sum over all Agent Versions, {{monitor_pair}}"
    }
   ]
  },
  {
   "title": "Bitswap Realtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 76 },
     "options": {
      "content": "### Bitswap Realtime Analysis\n\nOur [plugin](https://github.com/trudi-group/ipfs-metric-exporter) exports all incoming Bitswap traffic and connection events via a TCP server.\nWe have a [client](https://github.com/trudi-group/ipfs-tools/tree/master/bitswap-monitoring-client), which connects to this, performs analyses, and exports results via Prometheus.\n\n#### Bitswap in a Nutshell\n\nBitswap sends messages between peers.\nFor recent versions of the protocol, each message may contain any combination of\n- A wantlist, which encapsulates requests. This can be either `full`, replacing the previous state at the remote peer, or incremental.\n- A list of blocks, addressed by their CID.\n- A list of block presence responses.\n\nA wantlist in turn contains a list of entries:\n- Request entries `WANT_HAVE` and `WANT_BLOCK`, in addition to an optional `send_dont_have` flag\n- `CANCEL` entries, which cancel an outstanding request.\n\nBlock presence responses are either `HAVE` or `DONT_HAVE`.\nThese are returned for `WANT_HAVE` requests.\nThe `DONT_HAVE` is optional, and returned if `send_dont_have` is requested.\nMost peers support this.\n\n#### Requests and Responses\n\nIn general, our monitoring nodes sit passively and record all incoming traffic.\nUsually, these incoming messages are requests only.  \nHowever, we recently added functionality to also query all of our peers via Bitswap, in a controlled manner.\nThis then leads to our monitors also received responses, in the form of blocks and block presences.\nThis generally happens in short, fast bursts, when we sample the network for a set of CIDs.\n\n#### Deduplication\n\nReal-time analyses performed use the raw, non-deduplicated Bitswap traffic recorded by the monitors.\nBitswap sends a lot of duplicate entries, most of which are useless, since the wantlist state is persisted on remote peers for as long as the connection is alive.\nThis is a known issue, and in the future we will also support analyzing deduplicated traffic."
     }
    },
    {
     "title": "Bitswap Messages Received/s",
     "type": "timeseries",
     "description": "Rate of Bitswap messages received per second.\nThis counts Bitswap _messages_, which in turn may include requests, responses, blocks, and block presences.\nCalculated over 30 minutes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "msg/s" } },
     "targets": [
      {
       "expr": "sum(rate(bitswap_messages_received[30m])) by (monitor)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Wantlists Received/s",
     "type": "timeseries",
     "description": "Rate of wantlists received per second, by whether they were full or incremental.\nThis counts messages for which the wantlist is not empty.\nCalculated over a 30 minute window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "wl/s" } },
     "targets": [
      {
       "expr": "(sum(rate(wantlists_received[30m])) by (monitor,full))",
       "legendFormat": "{{monitor}}, full={{full}}"
      }
     ]
    },
    {
     "title": "Wantlist Entries/s: Total, Requests Only, CANCEL Only",
     "type": "timeseries",
     "description": "Rate of wantlist entries received per second.\nIn sum over all entry types, request types only, and CANCEL types only.\nCalculated over a 30 minute window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "entries/s" } },
     "targets": [
      {
       "expr": "sum(rate(wantlist_entries_received[30m])) by (monitor)",
       "legendFormat": "{{monitor}} All Entries"
      },
      {
       "expr": "sum(rate(wantlist_entries_received{entry_type!=\"cancel\"}[30m])) by (monitor)",
       "legendFormat": "{{monitor}} Requests"
      },
      {
       "expr": "sum(rate(wantlist_entries_received{entry_type=\"cancel\"}[30m])) by (monitor)",
       "legendFormat": "{{monitor}} CANCELs"
      }
     ]
    },
    {
     "title": "Wantlist Entries Received/s",
     "type": "timeseries",
     "description": "Rate of wantlist entries received per second, by entry type and send_dont_have flag.\nThis is calculated over a 30 minute window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "entries/s" } },
     "targets": [
      {
       "expr": "sum(rate(wantlist_entries_received{entry_type!=\"unknown\"}[30m])) by (monitor, entry_type, send_dont_have)",
       "legendFormat": "{{monitor}}, {{entry_type}}, send_dont_have={{send_dont_have}}"
      }
     ]
    },
    {
     "title": "Bitswap Messages Received/s by Public Gateway Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "sum(rate(bitswap_messages_received[30m])) by (monitor, origin_is_gateway)",
       "legendFormat": "{{monitor}}, public_gateway={{origin_is_gateway}}"
      }
     ]
    },
    {
     "title": "Wantlist Entries Received/s by Public Gateway Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "sum(rate(wantlist_entries_received{entry_type!=\"cancel\",origin_country!=\"\"}[30m])) by (monitor, entry_type, origin_is_gateway)"
      }
     ]
    },
    {
     "title": "Block Presences Received/s",
     "type": "timeseries",
     "description": "The rate of block presence entries received per second.\nCalculated over a 30 minute window.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "pres/s" } },
     "targets": [
      {
       "expr": "sum(rate(bitswap_block_presences_received[30m])) by (monitor, presence_type)",
       "legendFormat": "{{monitor}} {{presence_type}}"
      }
     ]
    },
    {
     "title": "Blocks Received/s",
     "type": "timeseries",
     "description": "The rate of blocks received per second.\nCalculate over a 30 minute window.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "sum(rate(bitswap_blocks_received[30m])) by (monitor)",
       "legendFormat": "{{monitor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bitswap Geolocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 52 },
     "options": {
      "content": "### Bitswap Message and Connection Event Geolocation\n\nAddresses are located using the [MaxMind GeoLite2](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data) database.\n\n#### Countries\n\nCountries are named using the [celes](https://crates.io/crates/celes) crate, which translates ISO 3166-1 2-letter country codes to their full name.\n\n#### Counting\n\n\"Bitswap Messages\" counts **all** incoming messages.\n\"Bitswap Requests\" counts all **wantlist entries** which are not `CANCEL`s.\nSee the description of the Bitswap section for more information on this.\n\n#### Deduplication\n\nThe notice from the other Bitswap realtime analysis section applies.\n\n#### Aggregation\n\nNote that, for the aggregated values over longer durations, the results may be inaccurate if we don't have enough data for the window.\nThese metrics are also especially susceptible to downtime.\n\n#### Address Selection\n\nFor Bitswap messages, we ask the IPFS node for connections to that peer as soon as we receive a message.\nWe export this information together with the message via our plugin.\nWe then select the first non-relayed address out of those.\nIf no non-relayed connections to the peer exist, we mark its origin as `\"Unknown\"`.\nDue to the inherent racy-ness of Bitswap wiretapping and asking the peer store for connections to the peer, some messages have no origin, or out-of-date connection info.\nWe believe this does not happen often.\n\nFor connection events, we get the address as part of the event and use it.\n\nWantlist entries receive the origin country of the parent message.\n\n#### Error Handling\n\nThe `\"Unknown\"` group contains:\n- Relayed connections\n- Address for which no entry is in the database\n- Addresses for which the entry does not list a `country`\n\nThe `\"Error\"` group contains:\n- Addresses for which the lookup failed\n\n"
     }
    },
    {
     "title": "Bitswap Messages Received/s, by Origin Country",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "msg/s" } },
     "targets": [
      {
       "expr": "sum(rate(bitswap_messages_received{origin_country!=\"\"}[30m])) by (origin_country)",
       "legendFormat": "{{origin_country}}"
      }
     ]
    },
    {
     "title": "Bitswap Requests Received/s by Origin Country",
     "type": "timeseries",
     "description": "Rate of non-CANCEL wantlist entries received per second.\nCalculated over a 30 minute window.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(wantlist_entries_received{entry_type!=\"cancel\",origin_country!=\"\"}[30m])) by (origin_country)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Top 10 Requesting Countries, Last 24h",
     "type": "bargauge",
     "description": "Rate of non-CANCEL wantlist entries received per second.\nCalculated over a one-day window.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(wantlist_entries_received{entry_type !=\"cancel\", origin_country!=\"\"}[1d])) by (origin_country))",
       "legendFormat": "{{origin_country}}"
      }
     ]
    },
    {
     "title": "Top 10 Requesting Countries, Last 7d",
     "type": "bargauge",
     "description": "Rate of non-CANCEL wantlist entries received per second.\nCalculated over a seven-day window.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(wantlist_entries_received{entry_type !=\"cancel\", origin_country!=\"\"}[7d])) by (origin_country))",
       "legendFormat": "{{origin_country}}"
      }
     ]
    },
    {
     "title": "Top 10 Requesting Countries, Last 30d",
     "type": "bargauge",
     "description": "Rate of non-CANCEL wantlist entries received per second.\nCalculated over a thirty-day window.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,sum(rate(wantlist_entries_received{entry_type !=\"cancel\", origin_country!=\"\"}[30d])) by (origin_country))",
       "legendFormat": "{{origin_country}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Connectivity and Network-Level Measurements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 185 },
     "options": {
      "content": "### IPFS Node Connectivity and Network-level Metrics\n\nIPFS itself exports various metrics about its connectivity.\nWe augment those with our plugin, adding information about open streams, supported protocols among connected peers, and others.\n\n#### Counting\n\nSome care must be taken to counting peers:  \nIPFS can hold multiple connections to the same peer.\nIPFS itself [used to](https://github.com/ipfs/go-ipfs/issues/8573) count and report connections, but this has changed in recent versions.\n\nWe try to make it obvious in all our visualizations, which way we're counting.\nPlease also refer to the respective descriptions.\n\n#### Agent Versions\n\nAs agent versions are somewhat user-chosen, we limit the number of agent versions we report on using the plugin, in order not to generate a large amount of timeseries in prometheus.\n\n#### Plugin-internal Metrics\n\nRecent versions of our [plugin](https://github.com/trudi-group/ipfs-metric-exporter) contain functionality to broadcast Bitswap requests to all connected peers in a controlled manner.\nThis is used to discover the locations of, and track CIDs over time.\n\nIn order for this to function, the plugin tries to maintain a Bitswap sender to every connected peer.\nThis is achieved through listening to connection events generated by IPFS.\nThese events are a bit racy and unreliable, and generally lag behind the true state of affairs a bit.\nAs such, we export metrics about the \"view\" of peers and connections from the point of view of the plugin, as well as how many Bitswap senders are currently available."
     }
    },
    {
     "title": "Number of Peers/Connections",
     "type": "timeseries",
     "description": "The number of open connections, in sum over all transports.\nThis counts multiple connections to the same peer multiple times, for older versions of IPFS.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(ipfs_p2p_peers_total) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of Peers/Connections by Transport",
     "type": "timeseries",
     "description": "The number of open connections, by transport.\nThis counts multiple connections to the same peer multiple times, for older versions of IPFS.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "ipfs_p2p_peers_total", "legendFormat": "{{instance}} {{transport}}" }
     ]
    },
    {
     "title": "Number of DHT Servers/Clients among Connected Peers",
     "type": "timeseries",
     "description": "The number of DHT servers vs. non-DHT servers, i.e. clients, among the peers we are connected to.\nThis is calculated based on whether the peer reports that they speak the /ipfs/kad/1.0.0 protocol.\nThis counts by peer ID.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(plugin_metric_export_peers_supported_protocols{protocol=\"/ipfs/kad/1.0.0\"}) by (instance)",
       "legendFormat": "{{instance}} DHT Servers"
      },
      {
       "expr": "(sum by (instance) (plugin_metric_export_peers_by_agent_version)) - (sum by (instance) (plugin_metric_export_peers_supported_protocols{protocol=\"/ipfs/kad/1.0.0\"}))",
       "legendFormat": "{{instance}} DHT Clients"
      }
     ]
    },
    {
     "title": "Supported Protocols of Connected Peers",
     "type": "timeseries",
     "description": "Sum of supported protocols over all currently connected peers, as reported by the IPFS node.\nThis counts by peer ID.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "plugin_metric_export_peers_supported_protocols",
       "legendFormat": "{{instance}} {{protocol}}"
      }
     ]
    },
    {
     "title": "Plugin: Available Bitswap Senders and Tracked Peers/Connections",
     "type": "timeseries",
     "description": "The plugin attempts to hold a Bitswap sender to every peer the node is connected to.\nIn order to do this, it uses connection notification mechanisms of the IPFS node, which are a bit imprecise and usually lag behind the true connectivity of the node.\nThis tracks the number of peers, connections, and available Bitswap senders, for the plugin.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "plugin_metric_export_bitswap_senders",
       "legendFormat": "{{instance}} Available Bitswap Senders"
      },
      {
       "expr": "plugin_metric_export_wiretap_peers",
       "legendFormat": "{{instance}} Tracked Peers"
      },
      {
       "expr": "plugin_metric_export_wiretap_connections",
       "legendFormat": "{{instance}} Tracked Connections"
      }
     ]
    },
    {
     "title": "Agent Versions of Connected Peers",
     "type": "timeseries",
     "description": "Number of currently connected peers, distinguished by their agent_version. This counts by peer ID.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "plugin_metric_export_peers_by_agent_version",
       "legendFormat": "{{instance}} {{agent_version}}"
      }
     ]
    },
    {
     "title": "Number of Streams by Protocol and Direction",
     "type": "timeseries",
     "description": "Number of currently open streams, by protocol and direction, as reported by the IPFS node.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "plugin_metric_export_open_streams",
       "legendFormat": "{{instance}}, \"{{protocol}}\", {{direction}}"
      }
     ]
    },
    {
     "title": "Number of Peers",
     "type": "timeseries",
     "description": "The number of peers, as reported by the IPFS node's peer store.\nThis counts by peer ID.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(sum by (instance) (plugin_metric_export_peers_by_agent_version))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime/System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
     "options": {
      "content": "### Process and Go Runtime Metrics\r\n\r\nThis lists metrics exported by IPFS and the Go runtime, as well as system metrics."
     }
    },
    {
     "title": "CPU Seconds",
     "type": "timeseries",
     "description": "CPU time used, calculated over 30 minutes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total[30m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{instance}}" },
      {
       "expr": "process_resident_memory_bytes{job!=\"kubo\", job!=\"node-exporter\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "timeseries",
     "description": "Open file descriptor count",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "process_open_fds", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"kubo\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Uptime",
     "type": "timeseries",
     "description": "Uptime of the IPFS node (not the system)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{job=~\"kubo\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IPFS and Go Version",
     "type": "state-timeline",
     "description": "IPFS version running and Go compiler version used to produce it.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum without (version) (label_replace(go_info{job=\"kubo\"}, \"go_version\", \"$1\", \"version\", \"(.*)\")) * on (instance) group_left(version) ipfs_info",
       "legendFormat": "{{instance}}: {{go_version}}, IPFS v{{version}}"
      }
     ]
    },
    {
     "title": "System CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by(instance,mode)",
       "legendFormat": "{{mode}}"
      }
     ]
    }
   ]
  }
 ]
}